# Generated by Django 3.2.9 on 2022-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20220322_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='second_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
