# Generated by Django 3.2.9 on 2022-03-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_userprofile_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='second_name',
            new_name='surename',
        ),
    ]
