# Generated by Django 3.2.9 on 2022-03-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_auto_20220322_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
