# Generated by Django 3.2.9 on 2022-03-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0038_delete_plantwebuser'),
        ('home_app', '0011_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_plants_profile', to='plant_app.plant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wishlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_list_profile', to='plant_app.plant'),
        ),
    ]
