# Generated by Django 3.2.9 on 2022-03-05 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('watering_description', models.TextField()),
                ('solar_condiotions_description', models.TextField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='WindowSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_direction', models.IntegerField(choices=[(1, 'parapet wschodni'), (2, 'parapet zachodni'), (3, 'parapet północny'), (4, 'parapet południowy'), (5, 'parapet północno-zachodni'), (6, 'parapet północno-wschodni'), (7, 'parapet południowo-zachodni'), (8, 'parapet południowo-wschodni')])),
                ('plants', models.ManyToManyField(to='plant_app.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantWebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('my_plants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_plants', to='plant_app.plant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='plant_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='HomeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_room', models.IntegerField(choices=[(1, 'kuchnia'), (2, 'łazienka'), (3, 'pokój')])),
                ('plants', models.ManyToManyField(to='plant_app.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence', models.IntegerField(choices=[(1, 'szkodliwa dla zwierząt'), (2, 'przyjazna dla zwierząt')])),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant_app.plant')),
            ],
        ),
    ]
