# Generated by Django 3.2.9 on 2022-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(blank=True),
        ),
    ]
