# Generated by Django 3.2.9 on 2022-03-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0002_category_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
