# Generated by Django 3.2.9 on 2022-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0005_alter_category_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
