# Generated by Django 3.2.9 on 2022-03-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0006_alter_category_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(blank=True, height_field=20, null=True, upload_to='images/', width_field=20),
        ),
    ]
