# Generated by Django 3.2.9 on 2022-03-08 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0007_alter_category_category_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPurifying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purifying', models.IntegerField(choices=[(1, 'oczyszczające powietrze'), (2, 'brak wpływu na oczyszczanie powietrza')])),
            ],
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='date_added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='solar_condiotions_description',
            new_name='solar_description',
        ),
        migrations.RemoveField(
            model_name='animalinfluence',
            name='plant',
        ),
        migrations.AddField(
            model_name='plant',
            name='animal_influence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animal_influence', to='plant_app.animalinfluence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='plant_app.category'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='air_purifying',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air_purifying', to='plant_app.airpurifying'),
            preserve_default=False,
        ),
    ]
