# Generated by Django 3.2.9 on 2022-03-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0008_auto_20220308_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
