# Generated by Django 3.2.9 on 2022-03-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0009_plant_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='air_purifying',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='animal_influence',
        ),
        migrations.AddField(
            model_name='plant',
            name='influence',
            field=models.IntegerField(choices=[(1, 'szkodliwa dla zwierząt'), (2, 'przyjazna dla zwierząt')], default=1),
        ),
        migrations.AddField(
            model_name='plant',
            name='purifying',
            field=models.IntegerField(choices=[(1, 'oczyszczające powietrze'), (2, 'brak wpływu na oczyszczanie powietrza')], default=1),
        ),
        migrations.DeleteModel(
            name='AirPurifying',
        ),
        migrations.DeleteModel(
            name='AnimalInfluence',
        ),
    ]
