# Generated by Django 3.2.9 on 2022-03-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0010_auto_20220308_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPurifying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purifying', models.IntegerField(choices=[(1, 'oczyszczające powietrze'), (2, 'brak wpływu na oczyszczanie powietrza')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence', models.IntegerField(choices=[(1, 'szkodliwa dla zwierząt'), (2, 'przyjazna dla zwierząt')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='influence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant_app.animalinfluence'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='purifying',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant_app.airpurifying'),
        ),
    ]
