# Generated by Django 3.2.9 on 2022-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0011_auto_20220309_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpurifying',
            name='purifying',
            field=models.IntegerField(choices=[(1, 'oczyszczająca powietrze'), (2, 'brak wpływu na oczyszczanie powietrza')], default=1),
        ),
        migrations.AlterField(
            model_name='windowside',
            name='window_direction',
            field=models.IntegerField(choices=[(1, 'okno w kierunku wschodnim'), (2, 'okno w kierunku zachodnim'), (3, 'okno w kierunku północnym'), (4, 'okno w kierunku południowym'), (5, 'okno w kierunku północno-zachodnim'), (6, 'okno w kierunku północno-wschodnim'), (7, 'okno w kierunku południowo-zachodnim'), (8, 'okno w kierunku południowo-wschodnim')]),
        ),
        migrations.CreateModel(
            name='RoomPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_part', models.IntegerField(choices=[(1, 'zacieniony kąt'), (2, 'słoneczny parapet')])),
                ('plants', models.ManyToManyField(to='plant_app.Plant')),
            ],
        ),
    ]
