# Generated by Django 3.2.9 on 2022-03-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0014_auto_20220310_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='airpurifying',
            name='influence_data',
            field=models.CharField(blank=True, max_length=126),
        ),
        migrations.AddField(
            model_name='airpurifying',
            name='influence_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animalinfluence',
            name='influence_data',
            field=models.CharField(blank=True, max_length=126),
        ),
        migrations.AddField(
            model_name='animalinfluence',
            name='influence_description',
            field=models.TextField(blank=True),
        ),
    ]
