# Generated by Django 3.2.9 on 2022-03-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0016_auto_20220310_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpurifying',
            name='purifying',
            field=models.IntegerField(choices=[(1, 'oczyszczająca powietrze'), (2, 'brak wpływu na oczyszczanie powietrza')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='animalinfluence',
            name='influence',
            field=models.IntegerField(choices=[(1, 'szkodliwa dla zwierząt'), (2, 'przyjazna dla zwierząt')], default=1, null=True),
        ),
    ]
