# Generated by Django 3.2.9 on 2022-03-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0019_auto_20220313_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_picture',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='homeroom',
            name='home_room',
            field=models.IntegerField(choices=[(1, 'kuchnia'), (2, 'łazienka'), (3, 'pokój dzienny')]),
        ),
        migrations.AlterField(
            model_name='windowside',
            name='window_direction',
            field=models.IntegerField(choices=[(1, 'okno w kierunku wschodnim'), (2, 'okno w kierunku zachodnim'), (3, 'okno w kierunku północnym'), (4, 'okno w kierunku południowym')]),
        ),
    ]
