# Generated by Django 3.2.9 on 2022-03-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0020_auto_20220314_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeroom',
            old_name='home_room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roompart',
            old_name='room_part',
            new_name='roompart',
        ),
        migrations.RenameField(
            model_name='windowside',
            old_name='window_direction',
            new_name='direction',
        ),
        migrations.AlterField(
            model_name='plantwebuser',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plantwebuser',
            name='my_plants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_plants_profile', to='plant_app.plant'),
        ),
        migrations.AlterField(
            model_name='plantwebuser',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plantwebuser',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plantwebuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plantwebuser',
            name='wish_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list_profile', to='plant_app.plant'),
        ),
        migrations.AlterField(
            model_name='windowside',
            name='plants',
            field=models.ManyToManyField(related_name='window_sides', to='plant_app.Plant'),
        ),
    ]
