# Generated by Django 3.2.9 on 2022-03-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0022_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
