# Generated by Django 3.2.9 on 2022-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0023_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeroom',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='roompart',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='windowside',
            name='plants',
        ),
        migrations.AddField(
            model_name='plant',
            name='direction',
            field=models.IntegerField(choices=[(1, 'okno w kierunku wschodnim'), (2, 'okno w kierunku zachodnim'), (3, 'okno w kierunku północnym'), (4, 'okno w kierunku południowym')], null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='room',
            field=models.IntegerField(choices=[(1, 'kuchnia'), (2, 'łazienka'), (3, 'pokój dzienny')], null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='roompart',
            field=models.IntegerField(choices=[(1, 'zacieniony kąt'), (2, 'słoneczny parapet')], null=True),
        ),
    ]
