# Generated by Django 3.2.9 on 2022-03-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0024_auto_20220316_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowSide',
        ),
    ]
