# Generated by Django 3.2.9 on 2022-03-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0025_delete_windowside'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeRoom',
        ),
        migrations.DeleteModel(
            name='RoomPart',
        ),
    ]
