# Generated by Django 3.2.9 on 2022-03-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0029_remove_plant_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roompart',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='windowside',
            name='plants',
        ),
        migrations.DeleteModel(
            name='HomeRoom',
        ),
        migrations.DeleteModel(
            name='RoomPart',
        ),
        migrations.DeleteModel(
            name='WindowSide',
        ),
    ]
