# Generated by Django 3.2.9 on 2022-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0033_plant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roompart',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='windowside',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeroom',
            name='room',
            field=models.IntegerField(choices=[(1, 'kuchnia'), (2, 'łazienka'), (3, 'pokój dzienny/ sypialnia')]),
        ),
    ]
