# Generated by Django 3.2.9 on 2022-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0034_auto_20220319_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompart',
            name='description',
            field=models.IntegerField(choices=[(1, 'Zacieniony kąt to warunki nieodpowiednie dla odmian o kolorowych liściach, które do rozwoju potrzebują większej ilości chlorofilu produkowanego w wyniku fotosyntezy. MNie kążda roślina znosi więc silne promieniowanie'), (2, 'Ustawiając kwiaty doniczkowe na parapecie okiennym trzeba uwzględnić to, że podczas wietrzenia – zwłaszcza zimą – chłodne powietrze może zagrażać roślinom, natomiast latem trzeba uważać, aby silnie operujące w dzień promienie słoneczne nie spowodowały poparzeń liści.')], null=True),
        ),
    ]
