# Generated by Django 3.2.9 on 2022-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0035_roompart_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='description',
            field=models.IntegerField(choices=[(1, 'Jeśli do tej pory nawet nie myślałeś ustawieniu roślin na kuchennym blacie z obawy o niekorzystne warunki tam panujące, mamy dla ciebie dobre wieści. Istnieje całkiem pokaźna lista roślin, którym bardzo odpowiada gorąca para, podwyższona wilgotność'), (2, 'Żywe kwiaty w łazience? Tak, to możliwe. Wbrew pozorom rośliny dobrze się czują w łazience, szczególnie te pochodzące z ciepłych i wilgotnych regionów. Wilgotny, ciepły i często zaciemniony klimat panujący w łazience to idealne warunki wzrostu dla wielu roślin doniczkowych. Czasem nawet zdecydowanie lepsze niż te panujące w pokojach, gdzie zbyt dużo światła i suche powietrze nie są korzystne dla wielu gatunków.'), (3, 'Pokój dzienny to na ogół miejsce tętniące życiem. Rośliny powinny więc być jak najbardziej zróżnicowane, ciekawe i kolorowe. Pokój dzienny, a także nasze sypialnie są jednak z reguły pomieszczeniami nieco bardziej suchymi niz pozostałe części naszego mieszkania. Jakie rośliny pasują do nich najlepiej?')], null=True),
        ),
        migrations.AddField(
            model_name='windowside',
            name='description',
            field=models.IntegerField(choices=[(1, 'Parapety okien wychodzących na wschód, podobnie jak tych zachodnich, zaledwie przez kilka godzin w ciągu dnia są w pełni nasłonecznione, przez resztę dnia oferując światło rozproszone. Sprawdzą się tu odmiany, które nie wymagają długotrwałego naświetlania do prawidłowego wzrostu.'), (2, 'Okno kwiatowe od zachodniej strony, podobnie jak wschodnie, nasłonecznione jest przez mniejszą część dnia. W tym przypadku promienie słoneczne padają bezpośrednio na rośliny po południu i wczesnym wieczorem. Czas ekspozycji na światło słoneczne jest więc podobny, przy czym okno zachodnie jest zdecydowanie cieplejsze niż wschodnie. Wiosną i latem promienie są dodatkowo dosyć silne, przez co mogą sparzyć liście delikatnych odmian. Które rośliny doniczkowe wybrać zatem na okno zachodnie? Którym niestraszne jest chwilowe zacienienie? Na parapecie zachodnim dobrze czuć się będą rośliny preferujące półcień lub lekkie nasłonecznienie.'), (3, 'Parapet okna skierowanego na północ to miejsce, w którym najtrudniej uprawiać rośliny domowe. Dlaczego? Przez większość dnia stojące na nim kwiaty nie mają bezpośredniego kontaktu z promieniami słonecznymi, otrzymując jedynie rozproszone, bardzo delikatne światło. Warunki takie są nieodpowiednie dla odmian o kolorowych liściach, które do rozwoju potrzebują większej ilości chlorofilu produkowanego w wyniku fotosyntezy. Nie sprawdzi się tu również większość doniczkowych roślin kwitnące, które zawiązują pączki kwiatowe wyłącznie przy dobrym nasłonecznieniu. Jakie więc rośliny uprawiać przy zachodnim oknie? Zasada jest prosta – sprawdzą się tu przede wszystkim odporne odmiany o ciemnozielonych liściach.'), (4, 'Okna południowe są najbardziej nasłonecznione, a przez to niemal równie wymagające przy uprawie roślin jak zacienione okna północne. Dlaczego? Większość roślin domowych nie akceptuje bezpośredniego silnego nasłonecznienia, które oferuje okno z wystawą południową. Efektem postawienia na parapecie południowym zbyt delikatnej rośliny może być jej zwiędnięcie z przesuszenia lub sparzenie liści. Warunki panujące na parapecie okna południowego można porównać do klimatu pustynnego, gdzie jest sucho i bardzo słonecznie. Jakie zatem kwiaty doniczkowe wybrać na południowe okno?')], null=True),
        ),
        migrations.AlterField(
            model_name='roompart',
            name='description',
            field=models.IntegerField(choices=[(1, 'Zacieniony kąt to warunki nieodpowiednie dla odmian o kolorowych liściach, które do rozwoju potrzebują większej ilości chlorofilu produkowanego w wyniku fotosyntezy. Nie każda roślina znosi więc silne promieniowanie.'), (2, 'Ustawiając kwiaty doniczkowe na parapecie okiennym trzeba uwzględnić to, że podczas wietrzenia – zwłaszcza zimą – chłodne powietrze może zagrażać roślinom, natomiast latem trzeba uważać, aby silnie operujące w dzień promienie słoneczne nie spowodowały poparzeń liści.')], null=True),
        ),
    ]
