# Generated by Django 3.2.9 on 2022-03-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0036_auto_20220319_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantwebuser',
            old_name='profile_pic',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='plant',
            name='purifying',
            field=models.IntegerField(choices=[(1, 'oczyszczające powietrze'), (2, 'brak wpływu na oczyszczanie powietrza')], default=1, null=True),
        ),
    ]
