# Generated by Django 3.2.9 on 2022-03-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0037_auto_20220319_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantWebUser',
        ),
    ]
