# Generated by Django 3.2.9 on 2022-03-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0040_auto_20220325_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyjungleboogie',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
