# Generated by Django 3.2.9 on 2022-03-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0041_scrapyjungleboogie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyjungleboogie',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
