# Generated by Django 3.2.9 on 2022-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0042_scrapyjungleboogie_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjungleboogie',
            name='picture',
            field=models.TextField(blank=True),
        ),
    ]
