# Generated by Django 3.2.9 on 2022-03-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0043_alter_scrapyjungleboogie_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyJungleBoogie',
        ),
    ]
