# Generated by Django 3.2.9 on 2022-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0045_scrapyjungleboogie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjungleboogie',
            name='price',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
