# Generated by Django 3.2.9 on 2022-03-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0047_alter_scrapyjungleboogie_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyJungleBoogie',
        ),
    ]
