# Generated by Django 3.2.9 on 2022-03-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0050_alter_scrapyjungleboogie_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyJungleBoogie',
        ),
    ]
