# Generated by Django 3.2.9 on 2022-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0052_scrapyjungleboogie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjungleboogie',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
