# Generated by Django 3.2.9 on 2022-03-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0055_scrapyjungleboogie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyJungleBoogie',
        ),
    ]
