# Generated by Django 3.2.9 on 2022-03-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0058_auto_20220328_2140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyZielonyParapet',
        ),
    ]
