# Generated by Django 3.2.9 on 2022-03-29 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0061_scrapyflorapoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyFloraPoint',
        ),
    ]
