# Generated by Django 3.2.9 on 2022-03-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0065_auto_20220330_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyCocaflora',
        ),
        migrations.DeleteModel(
            name='ScrapyFloraPoint',
        ),
        migrations.DeleteModel(
            name='ScrapyJungleBoogie',
        ),
        migrations.DeleteModel(
            name='ScrapyZielonyParapet',
        ),
    ]
