# Generated by Django 3.2.9 on 2022-03-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0067_scrapycocaflora_scrapyflorapoint_scrapyjungleboogie_scrapyzielonyparapet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyJungleBoogie',
        ),
    ]
