# Generated by Django 3.2.9 on 2022-03-31 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0075_scrapyjungleboogie_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapycocaflora',
            name='picture',
        ),
    ]
