# Generated by Django 3.2.9 on 2022-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0076_remove_scrapycocaflora_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapycocaflora',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
