# Generated by Django 3.2.9 on 2022-03-31 20:48

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0077_scrapycocaflora_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyflorapoint',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='scrapyjungleboogie',
            name='picture',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrapyzielonyparapet',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
