# Generated by Django 3.2.9 on 2022-04-01 16:30

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0080_alter_scrapyjungleboogie_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjungleboogie',
            name='picture',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True),
        ),
    ]
