# Generated by Django 3.2.9 on 2022-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0085_alter_scrapyjungleboogie_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyjungleboogie',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
