# Generated by Django 3.2.9 on 2022-04-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0086_alter_scrapyjungleboogie_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyjungleboogie',
            name='created',
        ),
        migrations.RemoveField(
            model_name='scrapyjungleboogie',
            name='link',
        ),
        migrations.RemoveField(
            model_name='scrapyjungleboogie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scrapyjungleboogie',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='scrapyjungleboogie',
            name='price',
        ),
        migrations.RemoveField(
            model_name='scrapyjungleboogie',
            name='updated',
        ),
    ]
