# Generated by Django 3.2.9 on 2022-04-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0087_auto_20220407_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyJungleBoogie',
        ),
    ]
